platform :ios, '11.0'

use_frameworks!

target 'KoalaTeaVideoEditor_Example' do
  pod 'KoalaTeaVideoEditor', :path => '../'

  target 'KoalaTeaVideoEditor_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.2'
  end
end
