use_frameworks!

target 'KoalaTeaVideoEditor_Example' do
  pod 'KoalaTeaVideoEditor', :path => '../'

  target 'KoalaTeaVideoEditor_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
